name: Lobby_by_Groodian
main: de.groodian.lobby.main.Main
author: Groodian
version: 2.0

commands:
   mpjoin:
      description: MinecraftParty
   lsetup:
      description: Lobby Setup
   build:
      description: Build